name: Native Glitch Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call Glitch API endpoint
        env:
          AUTHTOKEN: ${{ secrets.AUTHTOKEN }}
          PROJECTID: ${{ secrets.PROJECTID }}
          SOURCE_REPO: "justin0108/glitch-webpack-template"
        run: |
          curl -H "authorization: ${AUTHTOKEN}" -X POST "https://api.glitch.com/project/githubImport?projectId=${PROJECTID}&repo=${SOURCE_REPO}"
